{% set version = "1.1.0" %}

package:
  name: asn1crypto
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/asn1crypto/asn1crypto-{{ version }}.tar.gz
  sha256: 5abe83e773026162e4869f4ac16edf7554f661e8cc0bb6d2be3bc6915456731b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - asn1crypto

about:
  home: https://github.com/wbond/asn1crypto
  license: MIT
  license_file: LICENSE
  summary: Python ASN.1 library with a focus on performance and a pythonic API

extra:
  recipe-maintainers:
    - jschueller
    - ocefpaf
