appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: BiCz/984xSqhmvqTJ78x4DEqqdGDcMztbIfV0wJ99W5rO8wRJcU114wEmOQZWa1D97Uw6MYtW0zOVGcmNO9FzsdeMQ6WVN/6phpdqdra8ENm0Bxa6UCzlvg6YZHPN4tFnN5ArK0zxrkiHb4T8y59gd797urTLhRCwCwAiQ/rW1s6SU3sJ+eYTsEPSoejuHFCRlPNMBP/+cWTbjQk6kg+XW5IFCabAUKlj0/Jz4UnWm30Gnzx9DRcIX2HQ7OCEsM/qmI9PlLZiw99OmmqG03LT10qHgDbWKv5raM99o54Ybs7usj0EWHqIzVZSybjpgEmR6WMKKbdDAZxf/azWsp6LK1YS/HhtDyABEPJ/ZMmDP7Jh/tS2DmhegasGAV1/ye8kzEKXO7Bd51yaP7+TNPPOCEISPSCghr7zF/RudOPEABHBRwP7vi6kfczCNUf+Mt3jaXO9FaJNBysFARMni2XX6PN1klRBp7yYJvV/mTLTpesppApHbgooqOAMNr7i8prBvXkoT1wJ6EF8I4nyH78DZp1N3mSNHFcjsFiJhTcp+NkOsVmTHb70ijxkwtFeyaWCFS8ZSe4g84hmQ3gjUskoMZod6IP59TOhvZPLnbVttMsvnYjy/kbOX31pcBNUF1WX7pJUwjpfjUoT9zG7NiB+NTBLMkaWYUuL82VvfH5ED4=}
